// Comprobaciones del ACL y de la configuración de seguridad de Tauri.
//
// Se incluyen con `include!` en `build.rs` (fallan la compilación) y en `tests/acl.rs`
// (fallan `cargo test` aunque cargo no vuelva a ejecutar el script de compilación, por
// ejemplo si aparece un `tauri.windows.conf.json` sin tocar nada más). No se usa
// `rerun-if-changed` sobre archivos que no existen: cargo los da por cambiados siempre y
// recompilaría el núcleo en cada build.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

/// Comandos propios de Faro. Debe coincidir exactamente con los registrados en
/// `register_commands` (`src/lib.rs`). tauri-build genera con esta lista
/// `permissions/autogenerated/*.toml` (`allow-*`/`deny-*`, ignorados por git).
const COMMANDS: &[&str] = &[
    "engine_status",
    "engine_restart",
    "engine_call",
    "vault_list_keys",
    "vault_add_key",
    "vault_test_key",
    "vault_delete_key",
    "wp_plugin_export",
    "agents_pause_all",
    "agents_resume_all",
    "agents_control_state",
];

/// Únicos permisos que no son de Faro que la capability `main` puede conceder: la
/// interfaz solo escucha eventos del núcleo (`engine://status`). Sin `core:default`
/// (spec F1a §4.3). Añadir uno requiere revisión de seguridad.
const ALLOWED_FOREIGN_PERMISSIONS: &[&str] =
    &["core:event:allow-listen", "core:event:allow-unlisten"];

/// Único archivo permitido en `capabilities/`: Tauri carga cualquier capability de esa
/// carpeta (además de `app.security.capabilities` en tauri.conf.json, fijado a `main`).
const CAPABILITY_FILE: &str = "main.json";

/// Marca del registro de comandos; solo puede aparecer en `src/lib.rs`.
const HANDLER_MACRO: &str = "tauri::generate_handler![";

/// Devuelve la lista de incoherencias (vacía si todo cuadra).
fn check_acl(root: &Path) -> Vec<String> {
    let mut problems = Vec::new();
    let declared: BTreeSet<String> = COMMANDS.iter().map(|c| (*c).to_owned()).collect();
    if declared.len() != COMMANDS.len() {
        problems.push("COMMANDS (acl_checks.rs) tiene comandos repetidos".to_owned());
    }

    // 1. Registro: un solo `generate_handler!`, en src/lib.rs, con los mismos comandos.
    let mut handler_files = Vec::new();
    collect_handler_files(&root.join("src"), &mut handler_files, &mut problems);
    let lib_rs = root.join("src").join("lib.rs");
    if handler_files.len() != 1 || handler_files[0] != lib_rs {
        problems.push(format!(
            "`{HANDLER_MACRO}` debe aparecer una sola vez y solo en src/lib.rs; encontrado en {handler_files:?}"
        ));
    }
    match fs::read_to_string(&lib_rs) {
        Ok(source) => match registered_commands(&source) {
            Some(registered) => {
                for missing in declared.difference(&registered) {
                    problems.push(format!(
                        "`{missing}` está en COMMANDS (acl_checks.rs) pero no en generate_handler! (src/lib.rs)"
                    ));
                }
                for extra in registered.difference(&declared) {
                    problems.push(format!(
                        "`{extra}` está en generate_handler! (src/lib.rs) pero no en COMMANDS (acl_checks.rs)"
                    ));
                }
            }
            None => problems.push(format!("no se encontró `{HANDLER_MACRO}` en src/lib.rs")),
        },
        Err(error) => problems.push(format!("no se pudo leer src/lib.rs: {error}")),
    }

    // 2. Permisos escritos a mano (se ignora `permissions/autogenerated`).
    let permissions = handwritten_permissions(&root.join("permissions"), &mut problems);

    // 3. Capability `main`: único archivo de `capabilities/` y fijada en tauri.conf.json.
    check_capability_dir(&root.join("capabilities"), &mut problems);
    check_conf_capabilities(&root.join("tauri.conf.json"), &mut problems);
    check_extra_configs(root, &mut problems);
    check_capability_shape(
        &root.join("capabilities").join(CAPABILITY_FILE),
        &mut problems,
    );
    let granted = capability_permissions(
        &root.join("capabilities").join(CAPABILITY_FILE),
        &mut problems,
    );
    let own: BTreeSet<&String> = permissions
        .iter()
        .map(|(identifier, _)| identifier)
        .collect();
    for permission in &granted {
        if !own.contains(permission) && !ALLOWED_FOREIGN_PERMISSIONS.contains(&permission.as_str())
        {
            problems.push(format!(
                "capabilities/main.json concede `{permission}`, que no es un permiso de Faro ni está en ALLOWED_FOREIGN_PERMISSIONS (acl_checks.rs)"
            ));
        }
    }

    for command in &declared {
        let owners: Vec<&String> = permissions
            .iter()
            .filter(|(_, allowed)| allowed.contains(command))
            .map(|(identifier, _)| identifier)
            .collect();
        if owners.is_empty() {
            problems.push(format!(
                "`{command}` no tiene un permiso escrito a mano en permissions/*.toml"
            ));
        } else if !owners.iter().any(|owner| granted.contains(*owner)) {
            problems.push(format!(
                "`{command}`: ninguno de sus permisos ({owners:?}) está en capabilities/main.json"
            ));
        }
    }
    for (identifier, allowed) in &permissions {
        for command in allowed {
            if !declared.contains(command) {
                problems.push(format!(
                    "el permiso `{identifier}` permite `{command}`, que no está en COMMANDS (acl_checks.rs)"
                ));
            }
        }
    }
    problems
}

/// Archivos `.rs` bajo `dir` que contienen el registro de comandos.
fn collect_handler_files(
    dir: &Path,
    found: &mut Vec<std::path::PathBuf>,
    problems: &mut Vec<String>,
) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", dir.display()));
            return;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_handler_files(&path, found, problems);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            match fs::read_to_string(&path) {
                Ok(source) => {
                    for _ in code_only(&source).matches(HANDLER_MACRO) {
                        found.push(path.clone());
                    }
                }
                Err(error) => problems.push(format!("no se pudo leer {}: {error}", path.display())),
            }
        }
    }
}

/// El código sin las líneas de comentario (`//`, `///`, `//!`), para no contar la
/// documentación que menciona el registro.
fn code_only(source: &str) -> String {
    source
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Nombres de los comandos dentro de `tauri::generate_handler![...]` (último segmento de la ruta).
fn registered_commands(source: &str) -> Option<BTreeSet<String>> {
    let source = code_only(source);
    let start = source.find(HANDLER_MACRO)? + HANDLER_MACRO.len();
    let body = &source[start..];
    let end = body.find(']')?;
    let names = body[..end]
        .lines()
        .map(|line| line.split("//").next().unwrap_or_default())
        .flat_map(|line| line.split(','))
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(|item| item.rsplit("::").next().unwrap_or(item).to_owned())
        .collect();
    Some(names)
}

/// `identifier -> commands.allow` de los `.toml` escritos a mano en `permissions/`.
fn handwritten_permissions(dir: &Path, problems: &mut Vec<String>) -> Vec<(String, Vec<String>)> {
    let mut result = Vec::new();
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", dir.display()));
            return result;
        }
    };
    let mut files: Vec<_> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "toml"))
        .collect();
    files.sort();
    for path in files {
        let table = match fs::read_to_string(&path)
            .map_err(|e| e.to_string())
            .and_then(|text| text.parse::<toml::Table>().map_err(|e| e.to_string()))
        {
            Ok(table) => table,
            Err(error) => {
                problems.push(format!("no se pudo leer {}: {error}", path.display()));
                continue;
            }
        };
        let Some(list) = table.get("permission").and_then(toml::Value::as_array) else {
            continue;
        };
        for permission in list {
            let identifier = permission
                .get("identifier")
                .and_then(toml::Value::as_str)
                .unwrap_or_default()
                .to_owned();
            let allowed = permission
                .get("commands")
                .and_then(|c| c.get("allow"))
                .and_then(toml::Value::as_array)
                .map(|items| {
                    items
                        .iter()
                        .filter_map(toml::Value::as_str)
                        .map(str::to_owned)
                        .collect()
                })
                .unwrap_or_default();
            result.push((identifier, allowed));
        }
    }
    result
}

/// `capabilities/` solo puede contener `main.json` (ni otros archivos ni carpetas).
fn check_capability_dir(dir: &Path, problems: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", dir.display()));
            return;
        }
    };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if name != CAPABILITY_FILE || !entry.path().is_file() {
            problems.push(format!(
                "capabilities/ solo puede contener {CAPABILITY_FILE}; sobra `{name}`"
            ));
        }
    }
}

/// `app.security.capabilities` de tauri.conf.json debe ser exactamente `["main"]`.
fn check_conf_capabilities(path: &Path, problems: &mut Vec<String>) {
    let value = match fs::read_to_string(path)
        .map_err(|e| e.to_string())
        .and_then(|text| {
            serde_json::from_str::<serde_json::Value>(&text).map_err(|e| e.to_string())
        }) {
        Ok(value) => value,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", path.display()));
            return;
        }
    };
    let expected = serde_json::json!(["main"]);
    if value.pointer("/app/security/capabilities") != Some(&expected) {
        problems.push(
            "tauri.conf.json: app.security.capabilities debe ser exactamente [\"main\"]".to_owned(),
        );
    }
}

/// Configuraciones que Tauri fusionaría con `tauri.conf.json` (por plataforma) o que la
/// sustituirían (`tauri.conf.json5`, `Tauri.toml`). Ninguna está permitida: podrían
/// cambiar `app.security.capabilities` sin pasar por estas comprobaciones.
fn is_extra_tauri_config(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    if lower == "tauri.conf.json" {
        return false;
    }
    let json_config = lower.starts_with("tauri.")
        && (lower.ends_with(".conf.json") || lower.ends_with(".conf.json5"));
    let toml_config = lower.starts_with("tauri") && lower.ends_with(".toml");
    json_config || toml_config
}

/// Falla si junto a tauri.conf.json hay otra configuración de Tauri.
fn check_extra_configs(root: &Path, problems: &mut Vec<String>) {
    let entries = match fs::read_dir(root) {
        Ok(entries) => entries,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", root.display()));
            return;
        }
    };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if is_extra_tauri_config(&name) {
            problems.push(format!(
                "`{name}`: no se permiten configuraciones de Tauri por plataforma ni alternativas a tauri.conf.json"
            ));
        }
    }
}

/// Claves permitidas en capabilities/main.json. Sin `remote` (orígenes remotos),
/// `webviews`, `platforms` ni `local`: la capability es solo de la ventana `main` local.
const CAPABILITY_KEYS: &[&str] = &[
    "$schema",
    "identifier",
    "description",
    "windows",
    "permissions",
];

/// Forma de capabilities/main.json: solo `CAPABILITY_KEYS`, `identifier == "main"` y
/// `windows == ["main"]`.
fn check_capability_shape(path: &Path, problems: &mut Vec<String>) {
    let value = match fs::read_to_string(path)
        .map_err(|e| e.to_string())
        .and_then(|text| {
            serde_json::from_str::<serde_json::Value>(&text).map_err(|e| e.to_string())
        }) {
        Ok(value) => value,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", path.display()));
            return;
        }
    };
    let Some(object) = value.as_object() else {
        problems.push("capabilities/main.json debe ser un objeto JSON".to_owned());
        return;
    };
    for key in object.keys() {
        if !CAPABILITY_KEYS.contains(&key.as_str()) {
            problems.push(format!(
                "capabilities/main.json: la clave `{key}` no está permitida (solo {CAPABILITY_KEYS:?})"
            ));
        }
    }
    if object.get("identifier") != Some(&serde_json::json!("main")) {
        problems.push("capabilities/main.json: `identifier` debe ser \"main\"".to_owned());
    }
    if object.get("windows") != Some(&serde_json::json!(["main"])) {
        problems
            .push("capabilities/main.json: `windows` debe ser exactamente [\"main\"]".to_owned());
    }
}

/// Identificadores de permiso concedidos en la capability.
fn capability_permissions(path: &Path, problems: &mut Vec<String>) -> BTreeSet<String> {
    let value = match fs::read_to_string(path)
        .map_err(|e| e.to_string())
        .and_then(|text| {
            serde_json::from_str::<serde_json::Value>(&text).map_err(|e| e.to_string())
        }) {
        Ok(value) => value,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", path.display()));
            return BTreeSet::new();
        }
    };
    value
        .get("permissions")
        .and_then(serde_json::Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|item| {
                    item.as_str()
                        .or_else(|| item.get("identifier").and_then(serde_json::Value::as_str))
                })
                .map(str::to_owned)
                .collect()
        })
        .unwrap_or_default()
}
