//! Script de compilación del núcleo.
//!
//! Declara explícitamente los comandos propios en el manifiesto de la app (`__app-acl__`).
//! Así Tauri aplica SIEMPRE el control de acceso a los comandos propios, aunque
//! desaparezcan los `.toml` de `permissions/`: sin manifiesto de app, Tauri deja pasar
//! cualquier comando de `generate_handler!` desde un origen local sin mirar capabilities.
//!
//! Además comprueba, antes de compilar, que la lista de comandos, `src/lib.rs`, los
//! permisos escritos a mano y la capability `main` coinciden. Si no, la compilación falla.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

/// Comandos propios de Faro. Debe coincidir exactamente con los registrados en
/// `register_commands` (`src/lib.rs`). tauri-build genera con esta lista
/// `permissions/autogenerated/*.toml` (`allow-*`/`deny-*`, ignorados por git).
const COMMANDS: &[&str] = &[
    "engine_status",
    "engine_restart",
    "vault_list_keys",
    "vault_add_key",
    "vault_test_key",
    "vault_delete_key",
];

/// Marca del registro de comandos; solo puede aparecer en `src/lib.rs`.
const HANDLER_MACRO: &str = "tauri::generate_handler![";

fn main() {
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=permissions");
    println!("cargo:rerun-if-changed=capabilities");

    let problems = check_acl(Path::new("."));
    if !problems.is_empty() {
        panic!(
            "El ACL de los comandos propios no es consistente:\n  - {}",
            problems.join("\n  - ")
        );
    }

    // tauri-build solo incrusta el manifiesto de Windows (Common Controls v6) en los
    // binarios. Las pruebas que construyen una app simulada (`tests/acl.rs`) lo
    // necesitan también o no arrancan (STATUS_ENTRYPOINT_NOT_FOUND).
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if target_os == "windows" && target_env == "msvc" {
        println!("cargo:rustc-link-arg-tests=/MANIFEST:EMBED");
        println!(
            "cargo:rustc-link-arg-tests=/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"
        );
    }

    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS));
    if let Err(error) = tauri_build::try_build(attributes) {
        panic!("tauri-build falló: {error:#}");
    }
}

/// Devuelve la lista de incoherencias (vacía si todo cuadra).
fn check_acl(root: &Path) -> Vec<String> {
    let mut problems = Vec::new();
    let declared: BTreeSet<String> = COMMANDS.iter().map(|c| (*c).to_owned()).collect();
    if declared.len() != COMMANDS.len() {
        problems.push("COMMANDS (build.rs) tiene comandos repetidos".to_owned());
    }

    // 1. Registro: un solo `generate_handler!`, en src/lib.rs, con los mismos comandos.
    let mut handler_files = Vec::new();
    collect_handler_files(&root.join("src"), &mut handler_files, &mut problems);
    let lib_rs = root.join("src").join("lib.rs");
    if handler_files.len() != 1 || handler_files[0] != lib_rs {
        problems.push(format!(
            "`{HANDLER_MACRO}` debe aparecer una sola vez y solo en src/lib.rs; encontrado en {handler_files:?}"
        ));
    }
    match fs::read_to_string(&lib_rs) {
        Ok(source) => match registered_commands(&source) {
            Some(registered) => {
                for missing in declared.difference(&registered) {
                    problems.push(format!(
                        "`{missing}` está en COMMANDS (build.rs) pero no en generate_handler! (src/lib.rs)"
                    ));
                }
                for extra in registered.difference(&declared) {
                    problems.push(format!(
                        "`{extra}` está en generate_handler! (src/lib.rs) pero no en COMMANDS (build.rs)"
                    ));
                }
            }
            None => problems.push(format!("no se encontró `{HANDLER_MACRO}` en src/lib.rs")),
        },
        Err(error) => problems.push(format!("no se pudo leer src/lib.rs: {error}")),
    }

    // 2. Permisos escritos a mano (se ignora `permissions/autogenerated`).
    let permissions = handwritten_permissions(&root.join("permissions"), &mut problems);

    // 3. Capability `main`.
    let granted =
        capability_permissions(&root.join("capabilities").join("main.json"), &mut problems);

    for command in &declared {
        let owners: Vec<&String> = permissions
            .iter()
            .filter(|(_, allowed)| allowed.contains(command))
            .map(|(identifier, _)| identifier)
            .collect();
        if owners.is_empty() {
            problems.push(format!(
                "`{command}` no tiene un permiso escrito a mano en permissions/*.toml"
            ));
        } else if !owners.iter().any(|owner| granted.contains(*owner)) {
            problems.push(format!(
                "`{command}`: ninguno de sus permisos ({owners:?}) está en capabilities/main.json"
            ));
        }
    }
    for (identifier, allowed) in &permissions {
        for command in allowed {
            if !declared.contains(command) {
                problems.push(format!(
                    "el permiso `{identifier}` permite `{command}`, que no está en COMMANDS (build.rs)"
                ));
            }
        }
    }
    problems
}

/// Archivos `.rs` bajo `dir` que contienen el registro de comandos.
fn collect_handler_files(
    dir: &Path,
    found: &mut Vec<std::path::PathBuf>,
    problems: &mut Vec<String>,
) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", dir.display()));
            return;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_handler_files(&path, found, problems);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            match fs::read_to_string(&path) {
                Ok(source) => {
                    for _ in code_only(&source).matches(HANDLER_MACRO) {
                        found.push(path.clone());
                    }
                }
                Err(error) => problems.push(format!("no se pudo leer {}: {error}", path.display())),
            }
        }
    }
}

/// El código sin las líneas de comentario (`//`, `///`, `//!`), para no contar la
/// documentación que menciona el registro.
fn code_only(source: &str) -> String {
    source
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Nombres de los comandos dentro de `tauri::generate_handler![...]` (último segmento de la ruta).
fn registered_commands(source: &str) -> Option<BTreeSet<String>> {
    let source = code_only(source);
    let start = source.find(HANDLER_MACRO)? + HANDLER_MACRO.len();
    let body = &source[start..];
    let end = body.find(']')?;
    let names = body[..end]
        .lines()
        .map(|line| line.split("//").next().unwrap_or_default())
        .flat_map(|line| line.split(','))
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(|item| item.rsplit("::").next().unwrap_or(item).to_owned())
        .collect();
    Some(names)
}

/// `identifier -> commands.allow` de los `.toml` escritos a mano en `permissions/`.
fn handwritten_permissions(dir: &Path, problems: &mut Vec<String>) -> Vec<(String, Vec<String>)> {
    let mut result = Vec::new();
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", dir.display()));
            return result;
        }
    };
    let mut files: Vec<_> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "toml"))
        .collect();
    files.sort();
    for path in files {
        let table = match fs::read_to_string(&path)
            .map_err(|e| e.to_string())
            .and_then(|text| text.parse::<toml::Table>().map_err(|e| e.to_string()))
        {
            Ok(table) => table,
            Err(error) => {
                problems.push(format!("no se pudo leer {}: {error}", path.display()));
                continue;
            }
        };
        let Some(list) = table.get("permission").and_then(toml::Value::as_array) else {
            continue;
        };
        for permission in list {
            let identifier = permission
                .get("identifier")
                .and_then(toml::Value::as_str)
                .unwrap_or_default()
                .to_owned();
            let allowed = permission
                .get("commands")
                .and_then(|c| c.get("allow"))
                .and_then(toml::Value::as_array)
                .map(|items| {
                    items
                        .iter()
                        .filter_map(toml::Value::as_str)
                        .map(str::to_owned)
                        .collect()
                })
                .unwrap_or_default();
            result.push((identifier, allowed));
        }
    }
    result
}

/// Identificadores de permiso concedidos en la capability.
fn capability_permissions(path: &Path, problems: &mut Vec<String>) -> BTreeSet<String> {
    let value = match fs::read_to_string(path)
        .map_err(|e| e.to_string())
        .and_then(|text| {
            serde_json::from_str::<serde_json::Value>(&text).map_err(|e| e.to_string())
        }) {
        Ok(value) => value,
        Err(error) => {
            problems.push(format!("no se pudo leer {}: {error}", path.display()));
            return BTreeSet::new();
        }
    };
    value
        .get("permissions")
        .and_then(serde_json::Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|item| {
                    item.as_str()
                        .or_else(|| item.get("identifier").and_then(serde_json::Value::as_str))
                })
                .map(str::to_owned)
                .collect()
        })
        .unwrap_or_default()
}
